### ISSUE TITLE
Generate prod db password into credentials

### ISSUE THREAD

**Issue by drnic** [scopeandgo/jumpstartpro_generators#3]
Add the following to `lib/templates/rails/credentials/credentials.yml.tt`:

```yaml
database:
  primary:
    username: postgres
    password: <%= SecureRandom.alphanumeric(32) %>
```

And figure out how to use it in `.kamal/secrets`
